version: '3.8'

services:
  mongo: mongo:4.4 # mongo:4.4 o mongo:latest
    image: 
    restart: always
    container_name: mongodb-challenge
    hostname: mongo-host
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"