version: '3.8'

services:

  micro-cuentas:
    build:
      context: ./microservicio-cuentas
    container_name: cuentas
    restart: always
    ports:
      - "8000:8000"

  micro-transacciones:
    build:
      context: ./microservicio-transacciones
    container_name: transacciones
    restart: always
    ports:
      - "8005:8005"
  
  # mongo: 
  #   image: mongo:4.4 # mongo:4.4 o mongo:latest
  #   restart: always
  #   container_name: mongodb-challenge
  #   hostname: mongo-host
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=root
  #   volumes:
  #     - ./data:/data/db
  #   ports:
  #     - "27017:27017"